skip_commits:
  # Mimic Travis-ci skip behavior.
  message: /ci skip/

environment:

  # As defined by Appveyor.
  SA_PASSWORD: "Password12!"

  BUILD_INSTALL_PREFIX: "C:\\usr\\local"

<<<<<<< HEAD
  FREETDS_VERSION: "1.1.20"
=======
  matrix:
  - PYTHON: "C:\\Python36-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"
    CTDS_STATIC_LINK_FREETDS: "1"

  - PYTHON: "C:\\Python26-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"
>>>>>>> origin/static-linking

  matrix:
  - PYTHON: "C:\\Python27-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"

  - PYTHON: "C:\\Python33-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"
    DISTUTILS_USE_SDK: "1"

  - PYTHON: "C:\\Python34-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"
    DISTUTILS_USE_SDK: "1"

  - PYTHON: "C:\\Python35-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"

  - PYTHON: "C:\\Python36-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"

  - PYTHON: "C:\\Python36-x64"
    SQLSERVER_INSTANCENAME: "SQL2008R2SP2"

  - PYTHON: "C:\\Python36-x64"
    SQLSERVER_INSTANCENAME: "SQL2012SP1"

  - PYTHON: "C:\\Python36-x64"
    SQLSERVER_INSTANCENAME: "SQL2014"

<<<<<<< HEAD
  - PYTHON: "C:\\Python36-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"

  - PYTHON: "C:\\Python37-x64"
    SQLSERVER_INSTANCENAME: "SQL2016"

=======
>>>>>>> origin/static-linking
# Note: Database services should *not* be specified in the services section.
# The database service will be explicitly started by the script which enables
# TCP/IP connections for the database.
services:

cache:
  - '%BUILD_INSTALL_PREFIX% -> appveyor\\install.ps1'
  - '%BUILD_INSTALL_PREFIX% -> appveyor.yml'

install:
<<<<<<< HEAD
  - choco install opencppcoverage
  - "powershell appveyor\\install.ps1"
=======
  - cmd: set
  - ps: "appveyor\\install.ps1"
>>>>>>> origin/static-linking

build_script:
  - cmd: set
  - ps: "appveyor\\build_script.ps1"

before_test:
  - cmd: set
  - ps: "appveyor\\before_test.ps1"

test_script:
  - cmd: set
  - ps: "appveyor\\test_script.ps1"

after_test:
  - cmd: set
  - ps: "appveyor\\after_test.ps1"
